### ISSUE TITLE
Enums code style

### ISSUE THREAD

**Issue by zloylos** [yandex/codestyle#34]
example: 
```js
var UpperCamelCase = {
    UPPER_CASE: 0,
    DELETED: 1,
    REED: 2
};
```
Let's discuss.

upd: add semi-colon.

**Comment by GREENpoint** [comment]
Looks nice, but missed closing semi-colon.

**Comment by zloylos** [comment]
UpperCamelCase for enums also using in Google

**Comment by dodev** [comment]
+1 for the `UpperCamelCase` and the `ALL_CAPS` for the property names.

I would like to throw in some ideas:
* Use [Object.freeze](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/freeze) as stated in the comments of this [SO answer](http://stackoverflow.com/a/287917/1134973). It will enforce read-only on JS-machine level.
* Use meaningful strings instead of numbers for the values. It will be a bit easier to debug.

**Comment by ikokostya** [comment]
+1 for this style:
* `enum` introduces "new type", like `class`. So `UpperCamelCase` style is consistent.
* Values of `enum` are immutable. It's consistent with style for constants.
* We also use `UpperCamelCase` when describe new type via `@typedef {SomeType}`  in `jsdoc`.

**Comment by GREENpoint** [comment]
@dodev Do not use Object.freeze use new language features like `const`. It provides more clear code without runtime.

+1 for meaningful strings.

**Comment by ikokostya** [comment]
> Use meaningful strings instead of numbers for the values. It will be a bit easier to debug.

In some cases I want use number:

```js
var RegionTypes = {
    CITY: 4,
    COUNTRY: 7
};
```
where values are identifiers.

Also enumeration has overhead (if optimization tool isn't used): you can bloat your code with constructions like this:

```js
var MapType = {
    HYBRID: 'hybrid',
    ROADMAP: 'roadmap',
    SATELLITE: 'satellite'
    TERRAIN: 'terrain'
};
```
Why not use `string` instead `enum` in this case?

**Comment by dodev** [comment]
@GREENpoint I also like the idea of using ES2015 constants, but `const` protects only the variable's value from overwriting. In the case of an Object, that's a reference, and the object itself can be altered by client code:
```javascript
const obj = {a:1}; // => {a:1}
obj = {b:2};
obj; // => {a:1}
obj.a = 2;
obj; // => {a:2}
```
On the other hand, if you're experienced enough js developer you already know that you shouldn't alter API instances from your client code. So adding just the semantic sugar `const` will be enough just to make to code more readable.

@ikokostya the only two reasons I can think of are:
 1) avoiding typos (you'll get undefined if you miss-typed the name of the property and it would be easier to catch).
 2) using property names instead of strings can be aided by developer tools - like your text editor or you IDE ca enable auto-completion for this enum, or the static code-analyzer can warn you if you miss-typed the name of the enum.

Never the less you have a valid point there about the name repetition. Maybe we should leave this part up to the user.

**Comment by dmikis** [comment]
There is also a case with "intrusive" enumerations, when enum constants are declared as static fields of a class in which desired enumeration is used. [Example](https://github.com/dmikis/subbotnik-msk-20151017/blob/master/src/GpuCpuTimeBar.js#L18-L21): consts `GPU_TIME` and `CPU_TIME` are meant as members of one enumeration, `GPU_CPU_ORDER` and `CPU_GPU_ORDER` – another one. But they all available as [static members](https://github.com/dmikis/subbotnik-msk-20151017/blob/master/src/EXT_disjoint_timer_query/main.js#L21). For such a case some JSDoc convention is needed.

**Comment by ikokostya** [comment]
> There is also a case with "intrusive" enumerations, when enum constants are declared as static fields of a class in which desired enumeration is used. Example: consts GPU_TIME and CPU_TIME are meant as members of one enumeration, GPU_CPU_ORDER and CPU_GPU_ORDER – another one. But they all available as static members. For such a case some JSDoc convention is needed.

In this case constants are part of existed type:

```js
class GpuCpuTimeBar {}

/**
 * @static
 * @const
 */
GpuCpuTimeBar.GPU_TIME = 'gpu';
```

If you want use this constants in jsdoc in another place I think you can declare enumeration in namespace:

```js
timebar::GpuCpuTimeBar
timebar::BarType
```

or event in class

```js
GpuCpuTimeBar.BarType
```

**Comment by GREENpoint** [comment]
@dodev UPPER_CASE_CONST_CONVENTION protects you from const object fields overloading.

**Comment by ikokostya** [comment]
@zloylos Can you make pull request?

**Comment by zloylos** [comment]
#36
